%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV)
Camera.fx: 614.918291 
Camera.fy: 617.128471
Camera.cx: 635.265398
Camera.cy: 377.167164

Camera.kinectdk: 1
Camera.k1: 0.08169331111351927
Camera.k2: -0.046195201015812426
Camera.p1: 0.0012333372743673005
Camera.p2: -0.0006100655327036554
# Camera.k3: 0.035496
# Camera.k4: 1.46064
# Camera.k5: 0.950368
# Camera.k6: 0.180062

# Camera frames per second
Camera.fps: 30.0

# IR projector baseline times fx (aprox.)
Camera.bf: 40.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 3000

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 10

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 15  #从20改成12后 就能运行了， 这是为什么？
ORBextractor.minThFAST: 5

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.1  # originally 0.6
Viewer.KeyFrameLineWidth: 2
Viewer.GraphLineWidth: 4
Viewer.PointSize: 2
Viewer.CameraSize: 0.15  # originally 0.7
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -10   # originally -10
Viewer.ViewpointZ: -0.1
Viewer.ViewpointF: 2000
Viewer.UsePangolin: 1

# dsp
YoloClasses: [56, 57, 2, 75, 60, 59, 62, 63, 73]
DecoderPaths: ["weights/deepsdf/chairs_64",
               "weights/deepsdf/sofas_64",
               "weights/deepsdf/cars_64",
               "weights/deepsdf/vases_64_c",
               "weights/deepsdf/tables_64",  #table is default object in my code, so it's essential to keep the table.
               "weights/deepsdf/beds_64",
               "weights/deepsdf/displays_64",
               "weights/deepsdf/laptops_64",
               "weights/deepsdf/books_64_c"]

# ros
use_ros: 1
DatasetPathRoot: "/home/robotlab/ws_3d_vp/src/QSP-SLAM-my/data/MySimDataset/GroundObjects"
Minimux_Points_To_Judge_Good: 20  #视情况，看是否要减小到5

# camera
Camera.width: 1280
Camera.height: 720
# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 0

# Close/Far threshold. Baseline times.
ThDepth: 40.0

# Deptmap values factor  
DepthMapFactor: 1  #对应32FC1

#物体检测
# Config path for Python detectors
DetectorConfigPath: configs/config_self_allobject_ground_kinectdk.json
Objects.maskErrosion: 5  #default 10

# 保存本地
saveobjects: 0
savepoints: 1
savePCDMap: 0

# chair转counch(沙发)
chair2counch: 0

# use_object
useObjectConstruct: 1
ComputeCuboidType: 1
# + 修改物体识别的物体种类
# /home/robotlab/ws_3d_vp/src/QSP-SLAM-my/reconstruct/contents.py

# 地面
ConstraintType: 1 #3 rostf; 2 imu; 1 yaml




#  相机俯视28度
# Tworld_camera.qw: -0.364187
# Tworld_camera.qx: 0.606109
# Tworld_camera.qy: 0.606109
# Tworld_camera.qz: -0.364187

#  相机俯视30度
# Euler angles (degrees) ZYX   [ x: 90, y: 0, z: -120.0000004 ]
# Quaternion [x, y, z, w]   [ -0.6123724, -0.6123724, 0.3535534, 0.3535534 ]
# Tworld_camera.qw:  0.3535534
# Tworld_camera.qx: -0.6123724
# Tworld_camera.qy: -0.6123724
# Tworld_camera.qz:  0.3535534

# #  相机俯视30度   对应gazebo相机移动参数3.5 2 30.0  0.1
# Tworld_camera.qw:  0.3535534
# Tworld_camera.qx: -0.6123724
# Tworld_camera.qy: 0.6123724
# Tworld_camera.qz:  -0.3535534
# Tworld_camera.tx: 0.0
# Tworld_camera.ty: 0.0
# Tworld_camera.tz: 2.0  

# #  相机俯视0度   对应gazebo相机移动参数3.5 1 20.0  1
# # https://www.andre-gaschler.com/rotationconverter/
# # Euler angles (degrees) ZYX   [ x: -90.0000003, y: 0, z: -90 ]
# # Quaternion [x, y, z, w] [ -0.5, 0.5, -0.5, 0.5 ]
# Tworld_camera.qx: -0.5
# Tworld_camera.qy: 0.5
# Tworld_camera.qz: -0.5
# Tworld_camera.qw: 0.5
# Tworld_camera.tx: 0.0
# Tworld_camera.ty: 0.0
# Tworld_camera.tz: 1.8

#  相机俯视12度  
# https://www.andre-gaschler.com/rotationconverter/
# Euler angles (degrees) ZYX   [ x: -102.0000003, y: 0, z: -90 ]
# Quaternion [x, y, z, w] [ -0.5495252, 0.5495252, -0.4449967, 0.4449967 ]
Tworld_camera.qx: -0.5495252
Tworld_camera.qy: 0.5495252
Tworld_camera.qz: -0.4449967
Tworld_camera.qw: 0.4449967
Tworld_camera.tx: 0.0
Tworld_camera.ty: 0.0
Tworld_camera.tz: 1.3

# #  相机俯视27.5度  
# # https://www.andre-gaschler.com/rotationconverter/
# # Euler angles (degrees) ZYX   [ x: -117.5.0000003, y: 0, z: -90 ]
# # Quaternion [x, y, z, w][ -0.604514, 0.604514, -0.3668281, 0.3668281 ]
# Tworld_camera.qx: -0.604514
# Tworld_camera.qy: 0.604514
# Tworld_camera.qz: -0.3668281
# Tworld_camera.qw: 0.3668281
# Tworld_camera.tx: 0.0
# Tworld_camera.ty: 0.0
# Tworld_camera.tz: 1.15